apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.commonLabels | nindent 6 }}
  replicas: {{ .Values.serverReplicaCount }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.commonLabels | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      volumes:
        - emptyDir: {}
          name: tmp
      containers:
        - name: {{ .Values.appName }}-server
          imagePullPolicy: Always
          image: {{ .Values.serverImage }}:{{ .Values.serverTag }}
          ports:
            - name: {{ .Values.clientPortName }}
              containerPort: {{ .Values.clientPort }}
            - name: {{ .Values.serverPortName }}
              containerPort: {{ .Values.serverPort }}

          {{- toYaml .Values.securityContext | nindent 10 }}
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi

          volumeMounts:
            - mountPath: /tmp
              name: tmp

          env:
            {{ $apiServerUrl := required ".Values.clusterApiServer must be set. Refer to the values.yaml" .Values.clusterApiServer }}

            - name: CLUSTER_API_SERVER
              value: {{ .Values.clusterApiServer }}

            - name: CONNECTOR_SERVICEACCOUNT_NAME
              value: {{ .Values.serviceAccountName }}

            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sessionSecretName }}
                  key: {{ .Values.sessionSecretKeyName }}

            - name: SESSION_STORE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sessionSecretName }}
                  key: {{ .Values.sessionStoreKeyName }}

            - name: SESSION_STORE_PATH
              value: /tmp/sessions
