apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serverServiceName }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
spec:
    type: ClusterIP
    selector:
      {{- toYaml .Values.commonLabels | nindent 6 }}
    ports:
    - port: 80
      targetPort: {{ .Values.serverPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clientServiceName }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: console-serving-cert
spec:
    type: ClusterIP
    selector:
      {{ toYaml .Values.commonLabels | nindent 6 }}
    ports:
    - port: 80
      targetPort: {{ .Values.clientPort }}
      protocol: TCP
