# Default values for openshift-actions-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: actions-connector

securityContext:
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL


# REQUIRED VALUE:
# This is the apps.<cluster url> subdomain.which may have been edited by the admin. There does not appear to be a user API to get this.
# the easiest way to get this is to `oc expose <some service>` and then look at its subdomain
# "$(oc whoami --show-server | cut -d'/' -f3 | cut -d':' -f1 | sed -e 's/api/apps/')"
# https://github.com/helm/helm/issues/2055
clusterAppsSubdomain: ""

# REQUIRED VALUE
# oc whoami --show-server
clusterApiServer: ""

################################################################################

serviceAccountName: github-actions
# A rolebinding is created with this role, allowing the application pod to
# modify resources in the namespace
serviceAccountRole: edit

################################################################################

sessionSecretName: connector-session-secrets
sessionSecretKeyName: session-secret
sessionStoreKeyName: session-store-secret

################################################################################

commonLabels:
  app: openshift-actions-connector

deploymentLabels:

################################################################################

serverReplicaCount: 1

serverImage: quay.io/tetchell/openshift-actions-connector
serverTag: latest

serverServiceName: actions-connector-server-svc
serverPort: 3003
serverPortName: server-port

################################################################################

# clientReplicaCount: 1

# clientImage: quay.io/tetchell/openshift-actions-connector-client
# clientTag: latest

clientServiceName: actions-connector-client-svc
clientPort: 3000
clientPortName: client-port
