# Default values for openshift-actions-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: actions-connector

securityContext:
  securityContext:
    # readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL

clusterDomain: apps.member.crt-stage.com

################################################################################

serverReplicaCount: 1

serverImage: quay.io/tetchell/openshift-actions-connector
serverTag: latest

serverServiceName: actions-connector-server-svc
serverPort: 3003
serverPortName: server-port

deploymentLabels:
  app: openshift-actions-connector
  # tier: server

################################################################################

clientReplicaCount: 1

# clientImage: quay.io/tetchell/openshift-actions-connector-client
# clientTag: latest

clientServiceName: actions-connector-client-svc
clientPort: 3000
clientPortName: client-port

# clientLabels:
  # app: openshift-actions-connector
  # tier: client
