# Default values for openshift-actions-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: actions-connector

securityContext:
  securityContext:
    # readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL

# https://github.com/helm/helm/issues/2055
# Retrieve yours with "oc whoami --show-server", omitting protocol, and port if it's given (usually 6443)
# and then use the apps subdomain instead of the api subdomain.
# You can also do "oc expose <some service> and get the subdomain from the route that generates
# I do not know how to find this domain programmatically
clusterDomain: ""

serviceAccountName: github-actions
# A (non-cluster) rolebinding is created with this role, allowing the application pod to
# modify resources in the namespace
serviceAccountRole: edit

################################################################################

commonLabels:
  app: openshift-actions-connector

deploymentLabels:
  app: openshift-actions-connector

################################################################################

serverReplicaCount: 1

serverImage: quay.io/tetchell/openshift-actions-connector
serverTag: latest

serverServiceName: actions-connector-server-svc
serverPort: 3003
serverPortName: server-port

################################################################################

# clientReplicaCount: 1

# clientImage: quay.io/tetchell/openshift-actions-connector-client
# clientTag: latest

clientServiceName: actions-connector-client-svc
clientPort: 3000
clientPortName: client-port
