apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sessionSecretName }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
type: Opaque
data:
  {{ .Values.sessionSecretKeyName }}: {{ uuidv4 | b64enc }}
  {{ .Values.sessionStoreKeyName }}: {{ uuidv4 | b64enc }}
