name: Build and run
on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Start
        run: |
          nohup npm run start > output.txt &
          sleep 5

      - name: Test
        run: |
          curl -sSf http://localhost:3003

      - name: Echo output
        run: |
          cat output.txt
