name: Build and run
on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build
