name: Docker build and run
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: |
          yarn lint

      - name: Build in docker
        run: |
          yarn docker-build

      - name: Run in docker
        run: |
          yarn docker-run-d
          sleep 10

      - name: Test
        shell: bash
        run: |
          set -eEx
          curl -sSf http://localhost:3000
          curl -sSf http://localhost:3003

      - name: Take down
        run: |
          docker stop $(docker ps -q)
