name: Docker build and run
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - name: Lint
        run: |
          npm run lint

      - name: Build in docker
        run: |
          npm run docker-build

      - name: Start in docker
        run: |
          nohup npm run docker-run > output.txt &
          sleep 5

      - name: Test
        run: |
          curl -sSf http://localhost:3000

      - name: Echo output
        if: always()
        run: |
          cat output.txt
