name: Test
on:
  push:
  workflow_dispatch:


jobs:
  test-v4:

    runs-on: ubuntu-latest

    steps:
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.3
        with:
          oc version: '4.7.19'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Interact with the cluster
        run: oc cluster status

  test-v3:
    runs-on: ubuntu-latest

    steps:
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.3
        with:
          oc version: 'v3.11.0'
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Interact with the cluster
        run: oc cluster status
